CC	= x86_64-cross-freebsd11-gcc
CFLAGS  ?= -Wall -fPIC -ggdb -O2 $(OPTS) $(INCLUDE) $(DEFINES)
LDFLAGS ?= -s -lpthread -lcrypto -lm -lrt -lz -L. 

OBJ			= bin/bsd-x64
EXECUTABLE 	= bin/tinysvcmdns-bsd-x64

include Makefile

